### ISSUE TITLE
Dropbox bug

### ISSUE THREAD

**Issue by sabitalizade** [boly38/node-mongotools#41]
dropbox dump is not working

**Comment by sabitalizade** [comment]
(node:48973) UnhandledPromiseRejectionWarning: #<Object>
(Use `node --trace-warnings ...` to show where the warning was created)
(node:48973) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48973) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by boly38** [comment]
Hi @sabitalizade 

welcome on this repo, and thank you for this report!

I do need to reproduce that in order to fix it.

Unfortunately I've not enough context to reproduce the `UnhandledPromiseRejectionWarning` error you are talking about. I've no the version and suppose you're talking about the latest one (`1.3.0`)

With #42 I added 
- the way to run a dropbox dump test when running all tests
- add [test readme](https://github.com/boly38/node-mongotools/tree/main/tests) to understand how to run them
- fix a minor issue on username/password detectio

Is it possible for you to clone this repo, and try to reproduce your issue with a test ? then provide me the mtOptions you're using (remove secret value of course)

In advance thanks.

**Comment by boly38** [comment]
your PR is in `2.0.0`, please [sabitalizade](https://github.com/sabitalizade) let me know if it's ok for you, feel free to re-open this bug if needed.
