### ISSUE TITLE
ERR_REQUIRE_ESM - node reports an error after import，

### ISSUE THREAD

**Issue by catkinmu** [boly38/node-mongotools#75]
![image](https://github.com/boly38/node-mongotools/assets/27178791/796a0e2d-9c65-4f03-98de-6d7dac5ee4ee)

**Comment by catkinmu** [comment]
What do I need to do

**Comment by boly38** [comment]
Hi @catkinmu 

Really sorry for the delay, I completely miss that repository issues since a while :/


I think you're trying to use this module from CommonJS project but this project is an ES Module
(Im not 100% sure but I think in state they are not compatibles :( or maybe with some glue I'm not aware of)
https://www.syncfusion.com/blogs/post/js-commonjs-vs-es-modules


I recommend - if your project is not too big - to move your project as an ES module so using "type : module" in your `package.json` and relying on `import` instead of `require`.. a more modern JS.

**Comment by boly38** [comment]
I'll add a mention in readme about commonjs to fix this kind of question in the future
