### ISSUE TITLE
Error invalid_grant : refresh token is malformed

### ISSUE THREAD

**Issue by olawalejuwonm** [boly38/node-mongotools#94]
Using dropboxToken has worked for me but the addition of     dropboxAppKey: MT_DROPBOX_APP_KEY,
      dropboxAppSecret: MT_DROPBOX_APP_SECRET,
      dropboxRefreshToken: MT_DROPBOX_REFRESH_TOKEN is giving me Error invalid_grant : refresh token is malformed
      
    I got the app refresh token from 

https://www.dropbox.com/oauth2/authorize?client_id=APP_KEY&response_type=code&token_access_type=offline

**Comment by boly38** [comment]
Hi @olawalejuwonm 

what you describe here is only the very first step; 
this authorize app page gives you as result "a temporary access code" that enable you to ask a refresh token

You will have to follow and understand [dropbox auth guide](https://developers.dropbox.com/fr-fr/oauth-guide)


---

In order to help, a console mode [step by step](https://github.com/boly38/dropbox-refresh-token?tab=readme-ov-file#console-mode-step-by-step-to-retrieve-dropbox-refreshtoken) can be used to understand how to get refresh token

1) authorize app (you described) => give you `shortLivedAccessCode`
2) `shortLivedAccessCode` + appKey+appSecret => give you `refreshToken`

end then with a (appKey+appSecret+)`refreshToken` you could always 
3++) ask `shortLivedAccessToken`

`shortLivedAccessToken` is required to use dropbox api

---
that's why here node-mongotols demand appKey+appSecret+refreshToken

**Comment by olawalejuwonm** [comment]
I still don't get it,  can't I get the long lived token using the Web?

**Comment by boly38** [comment]
since [2021](https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens#retiring-legacy-tokens) dropbox [developers apps portal](https://www.dropbox.com/developers/apps) no more let you get "long-lived" access token from their UI. 
Today the accessToken you get using the portal are "short-lived" (having `sl.` prefix: this means not so good for an offline/app use..).

---

>I still don't get it,

Ok no worry, lets do that

````
git clone https://github.com/boly38/dropbox-refresh-token.git
cd dropbox-refresh-token
npm install
````

put in (dropbox-refresh-token/)`.env` file following values (put your xxx,yyy values from dropbox UI):
```` 
DROPBOX_APP_KEY=xxx
DROPBOX_APP_SECRET=yyy
## get from step 2 then uncomment
## DROPBOX_SHORT_LIVED_ACCESS_CODE=zzz
```` 

then launch step by step to get refreshToken and follow instructions (app authorization to update & uncomment access code, then relaunch to get refresh_token value
````
node src/dropbox_refresh_token.js
````

**Comment by boly38** [comment]
Hi @olawalejuwonm 
now with [interactive mode (cf. §quickstart](https://github.com/boly38/dropbox-refresh-token?tab=readme-ov-file#quickstart) that make getting refresh-token more easy, I consider this question to solved and close this issue. 
But please let me know if you encounter some difficulties.
Best Regards
